project:
  type: book
  output-dir: _book

book:
  title: "Методичка по гидравлическому разрыву пласта"
  author: "khabibullinra"
  language: ru
  chapters:
    - index.qmd
    - lecture-01-intro.qmd
    - lecture-02-physics.qmd
    - lecture-03-productivity.qmd
    - lecture-04-optimization-well.qmd
    - lecture-05-optimization-field.qmd
    - lecture-06-fracture-conductivity.qmd
    - lecture-07-monitoring.qmd
    - lecture-08-design.qmd

  appendices:  
    - tutorial-01-frac-single-well.qmd
    - tutorial-02-frac-single-well-various.qmd
    - tutorial-03-frac-compare-analitical-numerical.qmd
    - tutorial-04-frac-sensitivity-analysis.qmd
    - tutorial-05-frac-optimisation.qmd
    - tutorial-06-frac-geology-influence.qmd
    - tutorial-07-sector-model-fracs.qmd
    - tutorial-08-sector-model-frac-tuning.qmd
    - tutorial-09-frac-design.qmd

format:
  html:
    theme: cosmo
    toc: true

crossref:
  fig-title: "Рисунок"
  tbl-title: "Таблица"
  eq-title: "Формула"
  fig-prefix: "Рисунок"
  tbl-prefix: "Таблица"
  eq-prefix: "Формула"
  title-delim: " —"
